### ISSUE TITLE
Error when no temp

### ISSUE THREAD

**Issue by djungelola** [kayjei/badtemp_karlskrona#3]
When value isnt a float the log file produces a lot of errors:
 File "/config/custom_components/badtemp_karlskrona/sensor.py", line 60, in update
    self._state = float(json["temperatureWater"])
ValueError: could not convert string to float: 'NaT'

**Comment by kayjei** [comment]
Testing in progress, fix to come

**Comment by djungelola** [comment]
Is this fixed?

**Comment by kayjei** [comment]
Fixed. If a sensor contain a non-float value, it will not be setup, just ignored

**Comment by djungelola** [comment]
Works perfect! Good job

**Comment by kayjei** [comment]
Update. In the dev-branch, all sensors will be created, no matter if temperature exist or not. If temperature is missing, the state will be Unknown until a float value is available
